# Generated by Django 4.2 on 2023-04-07 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('points', models.IntegerField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 16, 18, 738213))),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aswer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=500)),
                ('points', models.IntegerField()),
                ('answers', models.IntegerField()),
                ('views', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/questions/%y/%m/%d')),
                ('subject', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 16, 18, 737043))),
                ('slug', models.SlugField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 16, 18, 738213))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='stack_eng.answer')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='stack_eng.question'),
        ),
    ]
