# Generated by Django 4.2 on 2023-04-12 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_eng', '0003_alter_answer_pub_date_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 2, 8, 3, 303255)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 2, 8, 3, 309282)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 2, 8, 3, 303255)),
        ),
    ]
