# Generated by Django 4.2 on 2023-04-13 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_eng', '0013_alter_answer_pub_date_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='publisher',
            new_name='liked_by',
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 22, 57, 6, 310143)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 22, 57, 6, 310660)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 22, 57, 6, 311271)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 22, 57, 6, 308781)),
        ),
    ]
