# Generated by Django 4.2 on 2023-04-13 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack_eng', '0018_alter_answer_pub_date_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 52, 13, 811417)),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like', to='stack_eng.answer'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 52, 13, 814683)),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 52, 13, 812425)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 52, 13, 809911)),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 52, 13, 813672)),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_like', to='stack_eng.question'),
        ),
    ]
