# Generated by Django 4.2 on 2023-04-13 23:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack_eng', '0020_answerlike_question_alter_answer_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 13, 49, 97791)),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 13, 49, 99849)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 13, 49, 97791)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 13, 49, 96792)),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 13, 49, 98851)),
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 13, 49, 100421))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='stack_eng.question')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'saved_by')},
            },
        ),
    ]
