# Generated by Django 4.2 on 2023-04-14 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_eng', '0022_alter_answer_pub_date_alter_answerlike_like_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 22, 3, 29, 360770)),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 22, 3, 29, 361864)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 22, 3, 29, 360770)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 22, 3, 29, 346885)),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 22, 3, 29, 360770)),
        ),
        migrations.AlterField(
            model_name='save',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 22, 3, 29, 362445)),
        ),
    ]
